modules:
  - name: 'map'
  - name: 'static'
  - name: 'landing'
  - name: 'stories'

waitSeconds: 200

wrap: false

paths:
  # Libs
  amplify: "amplify/lib/amplify"
  underscore: "underscore/underscore"
  backbone: "backbone/backbone"
  jquery: "jquery/dist/jquery"
  d3: "d3/d3"
  topojson: "topojson/topojson"
  cartodb: "cartodb.js/index"
  moment: "moment/moment"
  text: "requirejs-text/text"
  mps: "minpubsub/minpubsub.src"
  _string: "underscore.string/dist/underscore.string.min"
  jqueryui: "jqueryui/ui/jquery.ui.widget"
  jqueryujs: "jquery-ujs/src/rails"
  markerclusterer: "gmaps-markerclusterer-plus/src/markerclusterer"
  geojsonArea: "geojson-area"
  uri: "uri-templates/uri-templates"
  handlebars: "handlebars/handlebars"
  slick: "slick.js/slick/slick.min"
  simplePagination: "jquery.simplePagination/jquery.simplePagination"
  # stories

  jquery_fileupload: "jquery-file-upload/js/jquery.fileupload"
  jquery_migrate: "jquery-migrate/jquery-migrate"
  geojson: "geojson-google-maps/GeoJSON"

  wax: "wax.g.min"
  store: "store"
  Class: "Class.js/Class"
  jasmine: "jasmine"

  # Map
  # router: "map/router"
  utils: "map/utils"
  # views: "map/views"
  # templates: "map/templates"
  # services: "map/services"
  # presenters: "map/presenters"
  # models: "map/models"
  # cartocss: "map/cartocss"

  # General
  abstract: "abstract"
  helpers: "helpers"
  templates: "templates"
  views: "views"

shim:
  underscore:
    exports: "_"
  _string:
    exports: "_string"
    deps:
      - "underscore"
  amplify:
    deps:
      - "jquery"
    exports: "amplify"
  backbone:
    deps:
      - "jquery"
      - "underscore"
    exports: "Backbone"
  jqueryui:
    deps:
      - "jquery"
    exports: "$"
  pagination:
    deps:
      - "jquery"
    exports: 'simplePagination'
  Class:
    exports: "Class"
  uri:
    exports: "UriTemplate"
  handlebars:
    exports: "Handlebars"


  geojson:
    exports: "geojson"

  jqueryujs:
    deps:
      - "jquery"
    exports: "jqueryujs"

  jquery_migrate: 
    deps:
      - "jquery"
    exports: "jquery_migrate"

  jquery_fileupload: 
    deps:
      - "jquery"
    exports: "jquery_fileupload"
